# NumPy Array Attributes

## Introduction

After creating a NumPy array, it is important to understand its structure and properties.

NumPy provides several built-in attributes that help us understand the shape, dimensions, size, and data type of an array.

These attributes are widely used in Data Science, Machine Learning, and Deep Learning because they help us inspect and validate datasets before performing analysis.

---

### Practical Implementation 1: Student Marks Dataset

In [ ]:
import numpy as np

student_marks = np.array([ [80, 90, 85],
    [70, 88, 92],
    [95, 91, 87],
    [78, 82, 89]
])

print(student_marks)


[[80 90 85]
 [70 88 92]
 [95 91 87]
 [78 82 89]]


### shape  → How many rows and columns?

In [3]:
print("Shape :", student_marks.shape)

Shape : (4, 3)


### ndim   → How many dimensions?

In [4]:
print("Dimension :", student_marks.ndim)

Dimension : 2


### size   → How many total values?

In [5]:
print("Size :", student_marks.size)

Size : 12


### dtype  → What type of data is stored?

In [7]:
print("Data Type :", student_marks.dtype)

Data Type : int64


# Practical Implementation 2: Employee Salary Dataset

In [8]:
import numpy as np

salary = np.array([
    [35000.50],
    [42000.75],
    [51000.25],
    [60000.00]
])

print("Shape:", salary.shape)
print("Dimensions:", salary.ndim)
print("Size:", salary.size)
print("Data Type:", salary.dtype)

Shape: (4, 1)
Dimensions: 2
Size: 4
Data Type: float64


# Practical Implementation 3: Image Processing

   Grayscale image represented as a matrix.

In [9]:
import numpy as np

image = np.array([
    [0, 255, 128],
    [100, 200, 50],
    [75, 150, 225]
])

print("Shape:", image.shape)
print("Dimensions:", image.ndim)
print("Size:", image.size)

Shape: (3, 3)
Dimensions: 2
Size: 9


# Practical Implementation 4: Machine Learning Dataset

In [10]:
import numpy as np

dataset = np.array([
    [22, 45000, 1],
    [25, 55000, 0],
    [30, 70000, 1],
    [35, 85000, 0]
])

print("Shape:", dataset.shape)
print("Dimensions:", dataset.ndim)
print("Size:", dataset.size)
print("Data Type:", dataset.dtype)

Shape: (4, 3)
Dimensions: 2
Size: 12
Data Type: int64


# Mini Project: Dataset Inspection

This is exactly what Data Scientists do after loading a dataset.

In [18]:
import numpy as np

sales = np.array([
    [10000, 12000, 15000],
    [11000, 13000, 14000],
    [12000, 14000, 16000]
])


print("Dataset Information")
print("_"* 19)

print("shape :", sales.shape)
print("Dimension :", sales.ndim)
print("size :", sales.size)
print("Data Type :", sales.dtype)

Dataset Information
___________________
shape : (3, 3)
Dimension : 2
size : 9
Data Type : int64




# Why Are Array Attributes Important?

Before working with any dataset, a Data Scientist needs answers to questions such as:

* How many rows and columns are present?
* How many dimensions does the data have?
* How many values are stored in the dataset?
* What is the data type of the values?

NumPy attributes provide this information quickly and efficiently.

---

# Important Array Attributes

NumPy provides four fundamental attributes:

```python
shape
ndim
size
dtype
```

These attributes are frequently used while performing data analysis and machine learning tasks.

---

# 1. shape

## Definition

The `shape` attribute returns the dimensions of an array.

For a two-dimensional array, it returns:

```text
(Number of Rows, Number of Columns)
```

### Example

```python
arr.shape
```

### Use Cases

* Understanding dataset structure
* Checking rows and columns
* Verifying data before model training

### Data Science Example

Suppose a dataset contains:

```text
1000 Students
5 Features
```

The shape will be:

```text
(1000, 5)
```

This means:

* 1000 rows (records)
* 5 columns (features)

---

# 2. ndim

## Definition

The `ndim` attribute returns the number of dimensions of an array.

### Types of Arrays

### One-Dimensional Array

```text
[10, 20, 30]
```

Dimension:

```text
1
```

---

### Two-Dimensional Array

```text
[
 [1, 2, 3],
 [4, 5, 6]
]
```

Dimension:

```text
2
```

---

### Three-Dimensional Array

Used in image processing and deep learning.

Dimension:

```text
3
```

---

## Use Cases

* Understanding data structure
* Working with images and tensors
* Preparing data for machine learning models

---

# 3. size

## Definition

The `size` attribute returns the total number of elements present in an array.

### Formula

```text
Rows × Columns
```

Example:

```text
Shape = (3, 4)

Size = 12
```

---

## Use Cases

* Counting observations
* Dataset validation
* Memory estimation

---

### Data Science Example

If a dataset contains:

```text
500 rows
8 columns
```

Total elements:

```text
500 × 8 = 4000
```

---

# 4. dtype

## Definition

The `dtype` attribute returns the data type of the elements stored in an array.

Examples:

```text
int64
float64
bool
str
```

---

## Why dtype is Important?

Machine Learning algorithms work primarily with numerical data.

Before training a model, it is important to ensure that the data types are correct.

---

### Examples

```text
Age      → Integer
Salary   → Float
Gender   → String
Purchased → Boolean
```

Checking `dtype` helps identify incorrect data types and data quality issues.

---

# Importance in Data Science

Array attributes are often the first things checked after loading data.

Typical workflow:

```text
Load Dataset
      ↓
Check Shape
      ↓
Check Dimensions
      ↓
Check Size
      ↓
Check Data Types
      ↓
Perform Analysis
```

Without understanding these attributes, it becomes difficult to work with real-world datasets.

---

# Summary

| Attribute | Purpose                      |
| --------- | ---------------------------- |
| shape     | Returns rows and columns     |
| ndim      | Returns number of dimensions |
| size      | Returns total elements       |
| dtype     | Returns data type            |

---

# Interview Questions

### What does shape return?

Returns the dimensions of an array.

---

### What does ndim return?

Returns the number of dimensions.

---

### What does size return?

Returns the total number of elements in an array.

---

### What does dtype return?

Returns the data type of array elements.

---

### Why is dtype important in Machine Learning?

Machine learning algorithms require numerical data. The dtype attribute helps identify and validate data types before model training.

---

# One-Line Revision

NumPy array attributes provide information about an array's structure, dimensions, size, and data type, making them essential for data analysis and machine learning.
