# Introduction

### Statistical functions are used to summarize, analyze, and understand data.

In Data Science, statistical functions help us answer questions such as:

What is the average value?
What is the highest value?
What is the lowest value?
How spread out is the data?

NumPy provides built-in statistical functions that perform these calculations efficiently.

---

# Why Statistical Functions Are Important?

### Statistical functions are widely used in:

    Data Analysis
    Exploratory Data Analysis (EDA)
    Machine Learning
    Feature Engineering
    Business Analytics

Before building a machine learning model, data scientists often analyze data using statistical functions.

---

# Important Statistical Functions

### 1. sum()

    Returns the total sum of all elements.  eg. np.sum()

In [1]:
import numpy as np

marks = np.array([80, 90, 75, 95, 88])

print(marks)

[80 90 75 95 88]


In [2]:
print(np.sum(marks))

428


### 2. mean()

    Returns the average value.

In [3]:
print(np.mean(marks))

85.6


### 3. median()

      Returns the middle value after sorting the data.

In [5]:
print(np.median(marks))

88.0


### 4. min()

     Returns the smallest value.  eg.np.min(arr)


In [6]:
print(np.min(marks))

75


### 5. max()

   Returns the largest value.  eg. np.max(arr)


In [7]:
print(np.max(marks))

95


### 6. std()

    Returns the standard deviation.   eg. np.std(arr)

    Standard deviation measures how much data varies from the mean.


In [8]:
print(np.std(marks))

7.172168430816444


### 7. var()

      Returns the variance. eg. np.var(arr)

      Variance measures the spread of data.


In [9]:
print(np.var(marks))

51.44000000000001



---

# Axis Parameter

The axis parameter allows calculations row-wise or column-wise.

### axis = 0

Column-wise operation.

### axis = 1

Row-wise operation.

In [10]:
import numpy as np

marks = np.array([
    [80, 90, 85],
    [70, 88, 92],
    [95, 91, 87]
])

print("Column-wise Sum")
print(np.sum(marks, axis=0))

print("\nRow-wise Sum")
print(np.sum(marks, axis=1))

Column-wise Sum
[245 269 264]

Row-wise Sum
[255 250 273]



---
### eg. Real Data Science Example 

In [11]:
import numpy as np

sales = np.array([
    10000,
    12000,
    15000,
    18000,
    17000
])

print("Total Sales:", np.sum(sales))
print("Average Sales:", np.mean(sales))
print("Highest Sales:", np.max(sales))
print("Lowest Sales:", np.min(sales))

Total Sales: 72000
Average Sales: 14400.0
Highest Sales: 18000
Lowest Sales: 10000


# Summary Table

| Function | Purpose | Example |
|-----------|----------|----------|
| np.sum() | Returns total sum of elements | np.sum(arr) |
| np.mean() | Returns average value | np.mean(arr) |
| np.median() | Returns middle value | np.median(arr) |
| np.min() | Returns smallest value | np.min(arr) |
| np.max() | Returns largest value | np.max(arr) |
| np.std() | Returns standard deviation | np.std(arr) |
| np.var() | Returns variance | np.var(arr) |



---
# Interview Questions

### 1. What is the purpose of statistical functions in NumPy?

Statistical functions help summarize, analyze, and understand numerical data efficiently.

---

### 2. What is the difference between mean and median?

Mean:
Average of all values.

Median:
Middle value after sorting the data.

---

### 3. Which function is used to calculate the average value?

```python
np.mean()