# NumPy Random Module

## Introduction

The NumPy Random Module is used to generate random numbers, random arrays, and random samples.

Random data is widely used in Data Science, Machine Learning, Deep Learning, simulations, and testing.

NumPy provides a collection of functions that make random number generation easy and efficient.

---

# Why Do We Need Random Numbers?

Random numbers are useful for:

* Creating sample datasets
* Data simulation
* Testing algorithms
* Machine Learning experiments
* Train-Test data splitting
* Initializing model parameters

---

# Important Random Functions

NumPy provides several functions for generating random values:

```python
np.random.rand()
np.random.randn()
np.random.randint()
np.random.choice()
np.random.seed()
```

---

# 1. np.random.rand()

Generates random floating-point numbers between:

```text
0 and 1
```

The values are uniformly distributed.

---

In [1]:
import numpy as np


In [27]:
# Example 

print(np.random.rand(5))

[0.35444646 0.81336595 0.24784955 0.45861133 0.87730142]



 ---
 
# 2. np.random.randn()

Generates random values from a normal distribution.

Characteristics:

* Mean ≈ 0
* Standard Deviation ≈ 1

This function is commonly used in Machine Learning and Deep Learning.

---

In [16]:
print(np.random.randn())

-0.09093823779375118


# 3. np.random.randint()

Generates random integer values within a specified range.

Example:

In [15]:
print(np.random.randint(1, 100, 5))

[23 69  7 24 63]


# 4. np.random.choice()

Selects random values from a given list or array.

Example:

In [20]:
list = ["Apple", "Pinapple", "Mongo", "Banana", "kivi", "Orange"]

print(np.random.choice(list))

Mongo


# 5. np.random.seed()

The seed function ensures reproducibility.

Example:

In [26]:
import numpy as np

np.random.seed(56)

print(np.random.randint(1, 100, 5))

[86 16 65 35 15]


# Combined Program

In [32]:
import numpy as np

np.random.seed(42)

print("Random Decimal Numbers")
print(np.random.rand(5))

print("\nRandom Numbers from Normal Distribution")
print(np.random.randn(5))

print("\nRandom Integers")
print(np.random.randint(1, 100, 5))

print("\nRandom Choice")
print(np.random.choice(["Python", "NumPy", "Pandas", "Machine Learning"]))

Random Decimal Numbers
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

Random Numbers from Normal Distribution
[ 0.27904129  1.01051528 -0.58087813 -0.52516981 -0.57138017]

Random Integers
[22 89 49 91 59]

Random Choice
Pandas



---

# Real Data Science Example

Generate Student Marks Dataset

In [41]:
import numpy as np

np.random.seed(42)

marks = np.random.randint(35, 100, 5)

print(marks)

[86 49 95 55 58]


In [42]:
print("Average Marks :", np.mean(marks))
print("Highest Marks :", np.max(marks))
print("Lowest Marks :", np.min(marks))

Average Marks : 68.6
Highest Marks : 95
Lowest Marks : 49


### rand()     → Random Decimal Numbers (0 to 1)

### randn()    → Random Numbers from Normal Distribution

### randint()  → Random Integers

### choice()   → Random Selection

### seed()     → Same Output Every Run

---

# Interview Questions

## 1. What is the NumPy Random Module?

The NumPy Random Module is used to generate random numbers, random arrays, and random samples for simulations, testing, and machine learning applications.

---

## 2. Why are random numbers used in Data Science?

Random numbers are used for:

* Data Sampling
* Simulations
* Train-Test Splitting
* Model Initialization
* Synthetic Dataset Generation

---

## 3. What does np.random.rand() do?

It generates random floating-point numbers between 0 and 1.

Example:

```python
np.random.rand(5)
```

---

## 4. What does np.random.randn() do?

It generates random numbers from a normal distribution.

Example:

```python
np.random.randn(5)
```

---

## 5. What is the difference between rand() and randn()?

### rand()

* Uniform Distribution
* Values between 0 and 1

### randn()

* Normal Distribution
* Mean ≈ 0
* Standard Deviation ≈ 1

---

## 6. What does np.random.randint() do?

It generates random integer values within a specified range.

Example:

```python
np.random.randint(1, 100, 5)
```

---

## 7. What does np.random.choice() do?

It randomly selects values from a given list or array.

Example:

```python
np.random.choice(["Python", "NumPy", "Pandas"])
```

---

## 8. What is np.random.seed()?

The seed() function is used to make random outputs reproducible.

Example:

```python
np.random.seed(42)
```

---

## 9. Why is seed() important in Machine Learning?

It ensures that experiments produce the same results every time, making debugging, testing, and model evaluation easier.

---

## 10. What happens if seed() is not used?

Random values will change every time the program runs.

---

## 11. What is reproducibility?

Reproducibility means obtaining the same results when running the same code multiple times.

---

## 12. Which function is used to generate random integers?

```python
np.random.randint()
```

---

## 13. Which function is used to generate random decimal values?

```python
np.random.rand()
```

---

## 14. Which function is used for random sampling?

```python
np.random.choice()
```

---

## 15. How is the NumPy Random Module used in Machine Learning?

* Dataset Generation
* Data Sampling
* Weight Initialization
* Train-Test Splitting
* Simulations

---

# Most Important Interview Questions

### Q1. Difference between rand() and randn()?

**Answer:**

rand() generates random values between 0 and 1 using a uniform distribution, whereas randn() generates values from a normal distribution with mean 0 and standard deviation 1.

---

### Q2. What is seed() and why is it important?

**Answer:**

seed() is used to generate the same random output every time the code runs. It helps make experiments reproducible.

---

### Q3. What is reproducibility?

**Answer:**

Reproducibility means getting the same results every time the same code is executed.

---

### Q4. What does randint() do?

**Answer:**

randint() generates random integer values within a specified range.

---

### Q5. What does choice() do?

**Answer:**

choice() randomly selects one or more values from a given list or array.

---

# One-Line Revision

rand()     → Random Decimal Numbers

randn()    → Normal Distribution

randint()  → Random Integers

choice()   → Random Selection

seed()     → Reproducible Results

---