# Boolean Masking in NumPy

## Introduction

Boolean Masking is a powerful technique in NumPy used to filter data based on conditions.

It creates a Boolean array containing `True` and `False` values. Elements that satisfy the condition are marked as `True`, while others are marked as `False`.

Boolean Masking is one of the most frequently used techniques in Data Science because it helps in selecting, filtering, and cleaning data efficiently.

---

# Why Use Boolean Masking?

Boolean Masking is widely used for:

* Data Filtering
* Data Cleaning
* Feature Selection
* Data Analysis
* Machine Learning
* Exploratory Data Analysis (EDA)

Instead of using loops, NumPy allows us to filter data using simple conditions.

---

# How Boolean Masking Works

Consider the following array:

```python
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
```

Apply a condition:

```python
print(arr > 25)
```

Output:

```python
[False False  True  True  True]
```

Explanation:

```text
10 > 25 → False
20 > 25 → False
30 > 25 → True
40 > 25 → True
50 > 25 → True
```

This Boolean array is called a Boolean Mask.

---

# Extracting Values Using Boolean Mask

We can use the Boolean Mask to filter data.

```python
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])
```

Output:

```python
[30 40 50]
```

Only elements satisfying the condition are returned.

---

# Comparison Operators Used in Boolean Masking

| Operator | Meaning                  |
| -------- | ------------------------ |
| >        | Greater Than             |
| <        | Less Than                |
| >=       | Greater Than or Equal To |
| <=       | Less Than or Equal To    |
| ==       | Equal To                 |
| !=       | Not Equal To             |

---

# Multiple Conditions

Boolean Masking also supports multiple conditions.

## AND Condition (&)

Returns values that satisfy both conditions.

```python
import numpy as np

marks = np.array([35, 45, 78, 25, 90])

print(marks[(marks >= 40) & (marks <= 80)])
```

Output:

```python
[45 78]
```

---

## OR Condition (|)

Returns values that satisfy at least one condition.

```python
import numpy as np

marks = np.array([35, 45, 78, 25, 90])

print(marks[(marks < 30) | (marks > 80)])
```

Output:

```python
[25 90]
```

---

# Importance in Data Science

Boolean Masking is extensively used in real-world projects.

Examples:

* Selecting customers above a certain age
* Filtering products with high sales
* Removing invalid data
* Detecting outliers
* Selecting specific categories

It is one of the most important techniques used during data preprocessing.

---

# Practical Example 1: Student Marks Analysis

```python
import numpy as np

marks = np.array([35, 45, 78, 25, 90])

print("Original Marks:")
print(marks)

print("\nPassed Students:")
print(marks[marks >= 40])

print("\nFailed Students:")
print(marks[marks < 40])
```

Output:

```python
Original Marks:
[35 45 78 25 90]

Passed Students:
[45 78 90]

Failed Students:
[35 25]
```

---

# Practical Example 2: Employee Salary Analysis

```python
import numpy as np

salary = np.array([25000, 50000, 70000, 30000, 90000])

print("Employees with Salary Greater Than 50000:")
print(salary[salary > 50000])
```

Output:

```python
[70000 90000]
```

---

# Practical Example 3: Data Cleaning

Removing invalid ages from a dataset.

```python
import numpy as np

ages = np.array([20, 25, -5, 30, -10, 40])

print("Valid Ages:")
print(ages[ages > 0])
```

Output:

```python
[20 25 30 40]
```

---

# Practical Example 4: Temperature Analysis

```python
import numpy as np

temperature = np.array([28, 35, 42, 30, 45])

print("Hot Days:")
print(temperature[temperature > 40])
```

Output:

```python
[42 45]
```

---

# Combined Practical Program

```python
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original Array:")
print(arr)

print("\nGreater Than 25:")
print(arr[arr > 25])

print("\nLess Than 40:")
print(arr[arr < 40])

print("\nEqual To 30:")
print(arr[arr == 30])

print("\nNot Equal To 30:")
print(arr[arr != 30])

marks = np.array([35, 45, 78, 25, 90])

print("\nMarks Between 40 and 80:")
print(marks[(marks >= 40) & (marks <= 80)])

print("\nMarks Less Than 30 OR Greater Than 80:")
print(marks[(marks < 30) | (marks > 80)])
```

---

# Summary Table

| Operation     | Example                 |
| ------------- | ----------------------- |
| Greater Than  | arr > 50                |
| Less Than     | arr < 50                |
| Equal To      | arr == 50               |
| Not Equal To  | arr != 50               |
| AND Condition | (arr > 20) & (arr < 80) |
| OR Condition  | (arr < 20) | (arr > 80) |

---

# Interview Questions

## 1. What is Boolean Masking?

Boolean Masking is a technique used to filter data based on conditions using True and False values.

---

## 2. Why is Boolean Masking important?

It helps in filtering, cleaning, and selecting relevant data efficiently.

---

## 3. What does the following statement return?

```python
arr > 50
```

It returns a Boolean array containing True and False values.

---

## 4. Which operators are used in Boolean Masking?

```text
>
<
>=
<=
==
!=
&
|
```

---

## 5. Where is Boolean Masking used in Data Science?

* Data Cleaning
* Data Filtering
* Feature Selection
* EDA
* Machine Learning

---

# One-Line Revision

Boolean Masking is a technique used to filter and select data using True/False conditions.
