# NumPy Indexing and Slicing

## Introduction

Indexing and slicing are used to access specific elements or a group of elements from a NumPy array.

These operations are important because in Data Science we rarely work with an entire dataset. Instead, we often select specific rows, columns, or values for analysis.

---

# What is Indexing?

Indexing is used to access a single element from an array.

Example:

```python
arr[0]
```

Indexing returns one value.

---

# What is Slicing?

Slicing is used to access multiple elements from an array.

Example:

```python
arr[1:5]
```

Slicing returns a subset of the array.

---

# Why is Indexing and Slicing Important?

Used for:

* Data Selection
* Data Cleaning
* Feature Selection
* Machine Learning
* Data Analysis

---


# Practical Implementation
### 1. Creating Sample Array

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


# Types of Indexing and Slicing
### 2. 1D Array Indexing

      Access individual elements.

In [6]:
print(arr[0])
print(arr[2])
print(arr[-1])
print(arr[-4])


10
30
50
20


### 3. 1D Array Slicing

In [13]:
print(arr[1:3])
print(arr[0:5])
print(arr[3:])
print(arr[:3])

[20 30]
[10 20 30 40 50]
[40 50]
[10 20 30]


### 4. Creating a 2D Array

In [14]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(data)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


### 5. 2D Array Indexing

In [20]:
print(data[0, 0])
print(data[2, 2])
print(data[2, 2])
print(data[1, 2])
print(data[2, 1])

10
90
90
60
80


### 6. Selecting Rows

In [24]:
print(data[0])
print(data[2])
print(data[1])

[10 20 30]
[70 80 90]
[40 50 60]


### 7. Selecting Columns

In [25]:
print(data[:, 0])

print(data[:, 1])

print(data[:, 2])

[10 40 70]
[20 50 80]
[30 60 90]


### 8. 2D Array Slicing

In [26]:
print(data[0:2, 0:2])

[[10 20]
 [40 50]]


### 9. Fancy Indexing

In [28]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[[0, 3, 4]])

[10 40 50]


### 10. Boolean Indexing

In [34]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])

[30 40 50]


# Types of Indexing and Slicing

## 1. 1D Array Indexing

Access individual elements.

---

## 2. 2D Array Indexing

Access elements using:

```python
arr[row, column]
```

---

## 3. 1D Array Slicing

Access a range of elements.

```python
arr[start:end]
```

---

## 4. 2D Array Slicing

Access specific rows and columns.

```python
arr[row_start:row_end,
    col_start:col_end]
```

---

## 5. Fancy Indexing

Select multiple elements at once.

---

## 6. Boolean Indexing

Select elements based on conditions.

Most important in Data Science.

---

# Summary

| Operation        | Purpose                      |
| ---------------- | ---------------------------- |
| Indexing         | Access single element        |
| Slicing          | Access multiple elements     |
| Fancy Indexing   | Select custom elements       |
| Boolean Indexing | Filter data using conditions |

---

# Interview Questions

### What is Indexing?

Indexing is used to access a single element from an array.

### What is Slicing?

Slicing is used to access multiple elements from an array.

### Difference Between Indexing and Slicing?

Indexing returns a single element, whereas slicing returns multiple elements.

### Why is Boolean Indexing important?

Boolean indexing is used for filtering and selecting data based on conditions.

---

# One-Line Revision

Indexing selects one element, while slicing selects a range of elements from a NumPy array.
