# NumPy Broadcasting

## Introduction

Broadcasting is a powerful feature in NumPy that allows arithmetic operations between arrays of different shapes.

It enables NumPy to automatically expand smaller arrays so that mathematical operations can be performed efficiently without using loops.

Broadcasting makes code simpler, faster, and more memory efficient.

---

# Why Do We Need Broadcasting?

Without Broadcasting:

```python
result = []

for num in arr:
    result.append(num + 10)
```

With Broadcasting:

```python
arr + 10
```

Broadcasting reduces code complexity and improves performance.

---


# Types of Broadcasting

## 1. Scalar Broadcasting

A single value is applied to every element of an array.

Example:

```python
arr + 10
arr * 2
arr - 5
```

---

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

In [4]:
## Scaler brodcasting

print(arr + 10)
print(arr - 4)
print(arr * 2)
print(arr / 2)

[20 30 40 50 60]
[ 6 16 26 36 46]
[ 20  40  60  80 100]
[ 5. 10. 15. 20. 25.]


# Array Broadcasting



In [5]:
# Array Broadcasting
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

print(arr1 + arr2)

[11 22 33]


# 2D and 1D Broadcasting


In [6]:
# 2D and 1D Broadcasting
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

vector = np.array([10, 20, 30])

print(matrix + vector)

[[11 22 33]
 [14 25 36]]


# Broadcasting in Data Science

Broadcasting is widely used in:

* Data Cleaning
* Feature Engineering
* Data Normalization
* Machine Learning
* Deep Learning

---

# Real-World Example

Suppose a company decides to give every employee a bonus of ₹5000.

Instead of updating each salary manually:

```python
salary + 5000
```

NumPy automatically adds the bonus to every employee's salary.

---

# Summary

| Concept             | Description                          |
| ------------------- | ------------------------------------ |
| Broadcasting        | Automatic expansion of arrays        |
| Scalar Broadcasting | Array with a single value            |
| Array Broadcasting  | Operations between compatible arrays |
| Main Benefit        | Faster computation without loops     |

---

# Interview Questions

### What is Broadcasting?

Broadcasting is NumPy's ability to perform operations on arrays with different shapes by automatically expanding smaller arrays.

---

### Why is Broadcasting Important?

Broadcasting improves performance and removes the need for explicit loops.

---

### What are the Broadcasting Rules?

1. Dimensions must be equal.
2. One dimension can be 1.
3. Otherwise, broadcasting is not possible.

---

### Why is Broadcasting Used in Data Science?

It is used for efficient mathematical operations, feature scaling, normalization, and data transformation.

---

# One-Line Revision

Broadcasting allows NumPy to perform mathematical operations on arrays of different shapes without using loops.
