# NumPy Array Creation
### Introduction

Before performing any operation in NumPy, we first need to create arrays.

NumPy provides multiple functions to create arrays efficiently.

### import numpy as np

In [1]:
import numpy as np

### 1. np.array()

      Used to create a NumPy array from a Python list.

In [2]:
import numpy as np 

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


### Creating a 2D Array

In [4]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### 2. np.zeros()

      Creates an array filled with zeros.

In [5]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


### 2D Ones Array

In [6]:
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


### 4. np.arange()

     Creates an array within a range.

Syntax
          np.arange(start, stop, step)

In [ ]:
# Example 1

arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [ ]:
# Example 2

arr = np.arange(1, 10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [9]:
# Example 3

arr = np.arange(1, 22, 2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21]


### 5. np.linspace()

      Creates evenly spaced values between two numbers.

### Syntax
      np.linspace(start, stop, number_of_values)

In [10]:
# np.linspace() creates equally spaced numbers between a start value and an end value.

import numpy as np 

arr = np.linspace(1, 10, 5)
print(arr)


[ 1.    3.25  5.5   7.75 10.  ]


### 6. np.eye()

      Creates an Identity Matrix.

In [12]:
import numpy as np

arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Difference Between arange() and linspace()

| arange()                   | linspace()                  |
| -------------------------- | --------------------------- |
| Uses step size             | Uses number of values       |
| Stop value may be excluded | Stop value included         |
| Integer based              | Often used for float values |

---

## Example

```python
print(np.arange(1, 10, 2))

print(np.linspace(1, 10, 5))
```

---

# Summary

### np.array()

Create array from list.

---

### np.zeros()

Create array filled with zeros.

---

### np.ones()

Create array filled with ones.

---

### np.arange()

Create array using range values.

---

### np.linspace()

Create evenly spaced values.

---

# Interview Questions

## What is np.array()?

Used to convert Python lists into NumPy arrays.

---

## Difference Between zeros() and ones()?

```python
np.zeros()
```

creates zeros.

```python
np.ones()
```

creates ones.

---

## Difference Between arange() and linspace()?

```python
arange()
```

uses step size.

```python
linspace()
```

uses number of values.

---

## Which function creates evenly spaced values?

```python
np.linspace()
```

---

# One-Line Revision

NumPy provides multiple array creation functions such as:

```python
np.array()
np.zeros()
np.ones()
np.arange()
np.linspace()
```

which are the foundation of all NumPy operations.
