# NumPy Reshaping Arrays

## Introduction

Reshaping is the process of changing the shape or dimensions of an array without changing its data.

In Data Science and Machine Learning, data often needs to be converted into different formats before analysis or model training. NumPy provides several functions to reshape arrays efficiently.

---

# Why Do We Need Reshaping?

Real-world datasets are not always available in the required format.

For example:

```text
Original Data
[1, 2, 3, 4, 5, 6]
```

may need to be converted into:

```text
[[1, 2, 3],
 [4, 5, 6]]
```

for machine learning or data analysis.

---

# What is Reshaping?

Reshaping changes the structure of an array while keeping the same data.

Example:

```text
1D Array → 2D Array
2D Array → 1D Array
2D Array → 3D Array
```

---


# Important Reshaping Functions

## 1. reshape()

The `reshape()` function is used to change the shape of an array.



In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


# 2. reshape(-1)

      NumPy automatically calculates the missing dimension.

In [7]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(-1, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(3, -1)

print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


# 3. flatten()

        Converts a multi-dimensional array into a 1D array.


In [10]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

new_arr = arr.flatten()

print(new_arr)

[1 2 3 4 5 6]


# 4. ravel()

      Converts a multi-dimensional array into a 1D array.

In [13]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

ravel_arr = arr.ravel()


print(ravel_arr)

[1 2 3 4 5 6]


### Difference Between flatten() and ravel()

In [14]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat_arr = arr.flatten()
ravel_arr = arr.ravel()

flat_arr[0] = 100
ravel_arr[1] = 200

print("Original Array")
print(arr)

print("\nFlatten Array")
print(flat_arr)

print("\nRavel Array")
print(ravel_arr)

Original Array
[[  1 200   3]
 [  4   5   6]]

Flatten Array
[100   2   3   4   5   6]

Ravel Array
[  1 200   3   4   5   6]



---

# Difference Between flatten() and ravel()

| flatten()         | ravel()           |
| ----------------- | ----------------- |
| Returns a copy    | Returns a view    |
| More memory usage | Less memory usage |
| Slower            | Faster            |

---

# 5. transpose()

      The transpose() function swaps rows and columns.

      Example:

      arr.T

      or

      arr.transpose()

In [18]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Method 1")
print(arr. T)


print("Method 2")
print(arr.transpose())

Method 1
[[1 4]
 [2 5]
 [3 6]]
Method 2
[[1 4]
 [2 5]
 [3 6]]


# Why is Reshaping Important in Data Science?

Reshaping is used in:

* Data Preprocessing
* Feature Engineering
* Machine Learning
* Deep Learning
* Image Processing

---

# Real-World Example

Suppose a dataset contains:

```text
Students × Subjects
```

```text
[[80, 90, 85],
 [70, 88, 92],
 [95, 91, 87]]
```

Using transpose:

```text
Subjects × Students
```

```text
[[80, 70, 95],
 [90, 88, 91],
 [85, 92, 87]]
```

This makes analysis easier depending on the requirement.

---

# Summary

| Function    | Purpose                         |
| ----------- | ------------------------------- |
| reshape()   | Change array shape              |
| reshape(-1) | Automatic dimension calculation |
| flatten()   | Convert to 1D (copy)            |
| ravel()     | Convert to 1D (view)            |
| transpose() | Swap rows and columns           |

---

# Interview Questions

### What is Reshaping?

Reshaping is the process of changing the structure of an array without changing its data.

---

### What is reshape() used for?

It is used to change the dimensions of an array.

---

### What does reshape(-1) do?

NumPy automatically calculates the missing dimension.

---

### What is flatten()?

It converts a multi-dimensional array into a one-dimensional array and returns a copy.

---

### What is ravel()?

It converts a multi-dimensional array into a one-dimensional array and returns a view whenever possible.

---

### Difference Between flatten() and ravel()?

flatten() returns a copy whereas ravel() returns a view.

---

### What does transpose() do?

It swaps rows and columns of an array.

---

# One-Line Revision

NumPy reshaping functions help change the structure of arrays without changing the underlying data.
