# NumPy Linear Algebra

## Introduction

Linear Algebra is one of the most important mathematical foundations of Data Science, Machine Learning, Deep Learning, and Artificial Intelligence.

Many machine learning algorithms use matrices and vectors internally to perform calculations and make predictions.

NumPy provides a powerful Linear Algebra module that allows us to perform matrix operations efficiently.

---

# Why Learn Linear Algebra in NumPy?

Linear Algebra is used in:

* Machine Learning
* Deep Learning
* Computer Vision
* Natural Language Processing
* Recommendation Systems
* Data Analysis

Understanding these concepts helps in understanding how machine learning models work internally.

---

### 1. Vectors and Matrices

In [1]:
import numpy as np

# Vector
v = np.array([1, 2, 3])

# Matrix
A = np.array([[1, 2],
              [3, 4]])

### 2. Matrix Operations

Addition / Subtraction

In [2]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = A + B

print(result)


[[ 6  8]
 [10 12]]


In [3]:
result = B - A

print(result)

[[4 4]
 [4 4]]


Matrix Multiplication

In [4]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = A @ B

print(result)

[[19 22]
 [43 50]]


Element-wise multiplication

In [5]:
A*B

array([[ 5, 12],
       [21, 32]])

3. Transpose

In [6]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]


4. Determinant

In [7]:
A = np.array([[1, 2],
              [3, 4]])

det = np.linalg.det(A)

print(det)

-2.0000000000000004


5. Inverse

In [8]:
A = np.array([[1, 2],
              [3, 4]])

inverse = np.linalg.inv(A)

print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
print(A @ inverse)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


### 8. Solving Linear Equations

Suppose:

        2x+y=5
        x+3y=6

In [10]:
A = np.array([[2, 1],
              [1, 3]])

B = np.array([5, 6])

solution = np.linalg.solve(A, B)

print(solution)

[1.8 1.4]


### 9. Eigenvalues and Eigenvectors

   Used in PCA, Machine Learning, Computer Vision, etc.

In [11]:
A = np.array([[4, 2],
              [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

In [12]:
print(eigenvalues)

[5. 2.]


In [13]:
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


### 10. Vector Norm

   Norm represents vector length.

In [14]:
v = np.array([3, 4])

print(np.linalg.norm(v))

5.0


### 11. Rank of Matrix

Rank tells the number of independent rows or columns.

In [15]:
A = np.array([[1, 2],
              [2, 4]])

print(np.linalg.matrix_rank(A))

1


| Function                  | Description                |
| ------------------------- | -------------------------- |
| `np.linalg.det()`         | Determinant                |
| `np.linalg.inv()`         | Matrix Inverse             |
| `np.linalg.solve()`       | Solve Linear Equations     |
| `np.linalg.eig()`         | Eigenvalues & Eigenvectors |
| `np.linalg.norm()`        | Vector/Matrix Norm         |
| `np.linalg.matrix_rank()` | Matrix Rank                |
| `A.T`                     | Transpose                  |
| `A @ B`                   | Matrix Multiplication      |



---

# Interview Questions

## 1. What is Linear Algebra in NumPy?

**Answer:**

Linear Algebra in NumPy is performed using the `numpy.linalg` module, which provides functions for matrix and vector operations such as matrix multiplication, determinant, inverse, eigenvalues, and solving linear equations.

---

## 2. What is the difference between `*` and `@`?

**Answer:**

### `*` Operator

Performs element-wise multiplication.

Example:

```python
A * B
```

### `@` Operator

Performs matrix multiplication.

Example:

```python
A @ B
```

---

## 3. What is a determinant?

**Answer:**

A determinant is a scalar value calculated from a square matrix that indicates whether the matrix is invertible.

Example:

```python
np.linalg.det(A)
```

---

## 4. When does a matrix have an inverse?

**Answer:**

A matrix has an inverse only when its determinant is not equal to zero.

```text
det(A) ≠ 0
```

If:

```text
det(A) = 0
```

the matrix is called a singular matrix and cannot be inverted.

---

## 5. Why is `np.linalg.solve()` preferred over `np.linalg.inv()`?

**Answer:**

`np.linalg.solve()` is preferred because:

* Faster
* More accurate
* Numerically stable
* Uses less computation

It directly solves:

```text
AX = B
```

without explicitly calculating the inverse matrix.

---

## 6. What are Eigenvalues and Eigenvectors?

**Answer:**

Eigenvalues and Eigenvectors describe important properties of matrix transformations.

They are widely used in:

* Principal Component Analysis (PCA)
* Machine Learning
* Computer Vision
* Dimensionality Reduction

Example:

```python
np.linalg.eig(A)
```

---

## 7. What is the norm of a vector?

**Answer:**

The norm represents the length or magnitude of a vector.

Example:

```python
np.linalg.norm(v)
```

Applications:

* Distance calculations
* Similarity measurement
* Machine Learning

---

## 8. What is matrix rank?

**Answer:**

Matrix rank is the number of linearly independent rows or columns in a matrix.

Example:

```python
np.linalg.matrix_rank(A)
```

Rank helps determine:

* Data redundancy
* Matrix invertibility
* Linear dependence

---

## 9. What is the transpose of a matrix?

**Answer:**

The transpose of a matrix is obtained by interchanging rows and columns.

Example:

```python
A.T
```

If:

```text
[[1 2 3]
 [4 5 6]]
```

Transpose:

```text
[[1 4]
 [2 5]
 [3 6]]
```

---

## 10. What are the applications of Linear Algebra?

**Answer:**

Linear Algebra is used in:

* Machine Learning
* Data Science
* Deep Learning
* Computer Vision
* Graphics
* Optimization
* Scientific Computing
* Recommendation Systems

Most machine learning algorithms internally perform matrix and vector operations.

---

# Most Important Interview Questions

### Q1. What is the difference between `*` and `@`?

**Answer:**

`*` performs element-wise multiplication, whereas `@` performs matrix multiplication.

---

### Q2. What is a determinant?

**Answer:**

A determinant is a scalar value that indicates whether a matrix can be inverted.

---

### Q3. When does a matrix have an inverse?

**Answer:**

A matrix has an inverse when its determinant is not equal to zero.

---

### Q4. What are Eigenvalues and Eigenvectors?

**Answer:**

They describe important properties of matrix transformations and are heavily used in PCA and Machine Learning.

---

### Q5. Why is Linear Algebra important in Machine Learning?

**Answer:**

Machine Learning algorithms represent data as matrices and perform matrix operations during training and prediction.

---

# One-Line Revision

```text
dot()            → Dot Product

@ or matmul()    → Matrix Multiplication

T                → Transpose

det()            → Determinant

inv()            → Inverse Matrix

eig()            → Eigenvalues & Eigenvectors

norm()           → Vector Length

matrix_rank()    → Matrix Rank
```
