# NumPy Array Operations

## Introduction

NumPy allows mathematical operations to be performed directly on arrays.

Unlike Python lists, NumPy can perform operations on all elements of an array simultaneously without using loops.

This feature is known as Vectorization.

---

# Why Array Operations Are Important?

Array operations are widely used in:

* Data Analysis
* Machine Learning
* Deep Learning
* Scientific Computing
* Feature Engineering

---

# What is Vectorization?

Vectorization means applying an operation to an entire array at once.

Example:

```python
arr * 2
```

Instead of using a loop, NumPy performs the operation on all elements efficiently.

---


# Types of Array Operations

## Arithmetic Operations

* Addition (+)
* Subtraction (-)
* Multiplication (*)
* Division (/)
* Power (**)

---

In [2]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([1, 2, 3, 4, 5])

print(arr1)
print(arr2)

[10 20 30 40 50]
[1 2 3 4 5]


In [4]:
print("Addition of arr :",arr1 + arr2)
print("Substraction :", arr1 - arr2)
print("Multipliction:" ,arr1 * arr2)
print("Division:", arr1 / arr2)

Addition of arr : [11 22 33 44 55]
Substraction : [ 9 18 27 36 45]
Multipliction: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]


###  Power Operation

In [5]:
print(arr1 ** 2)

[ 100  400  900 1600 2500]


###  Scalar Operations

In [7]:
# ADD 10 

print(arr1 + 10)

[20 30 40 50 60]


Multiply by 2

In [8]:
print(arr1 * 2)

[ 20  40  60  80 100]


## Comparison Operations

* Greater Than (>)
* Less Than (<)
* Equal To (==)
* Not Equal To (!=)

---

In [9]:
import numpy as np

marks = np.array([35, 45, 78, 25, 90])

# Greater Than
print(marks > 50)

# Less Than
print(marks < 50)

# Greater Than or Equal To
print(marks >= 40)

# Less Than or Equal To
print(marks <= 40)

# Equal To
print(marks == 78)

# Not Equal To
print(marks != 78)

# Values Greater Than 50
print(marks[marks > 50])

# Values Less Than 50
print(marks[marks < 50])

# Values Between 40 and 80
print(marks[(marks >= 40) & (marks <= 80)])

# Values Greater Than 80 or Less Than 30
print(marks[(marks > 80) | (marks < 30)])

# Passed Students (Marks >= 40)
print(marks[marks >= 40])

# Failed Students (Marks < 40)
print(marks[marks < 40])

[False False  True False  True]
[ True  True False  True False]
[False  True  True False  True]
[ True False False  True False]
[False False  True False False]
[ True  True False  True  True]
[78 90]
[35 45 25]
[45 78]
[25 90]
[45 78 90]
[35 25]



## Aggregation Operations

* sum()
* mean()
* min()
* max()
* std()

These operations summarize data and are heavily used in Data Science.

---

## Aggregation Operations

* sum()
* mean()
* min()
* max()
* std()

These operations summarize data and are heavily used in Data Science.

---

In [11]:
import numpy as np

marks = np.array([80, 90, 75, 95, 88])

In [18]:
print("Total mark :", np.sum(marks))
print("Avrage marks : ", np.mean(marks))
print("Lowest mark mark :", np.max(marks))
print("Higest mark :", np.max(marks))
print("Standard Deviation :", np.std(marks))

Total mark : 428
Avrage marks :  85.6
Lowest mark mark : 95
Higest mark : 95
Standard Deviation : 7.172168430816444


# Real Business Example
      
      Monthly Sales

In [19]:
sales = np.array([
    10000,
    12000,
    15000,
    18000,
    17000
])

print("Total Sales :", np.sum(sales))
print("Average Sales :", np.mean(sales))
print("Maximum Sales :", np.max(sales))

Total Sales : 72000
Average Sales : 14400.0
Maximum Sales : 18000


# Advantages of NumPy Operations

* Faster execution
* Less code
* Better readability
* Optimized for large datasets

---

# Summary

| Operation     | Purpose        |
| ------------- | -------------- |
| +             | Addition       |
| -             | Subtraction    |
| *             | Multiplication |
| /             | Division       |
| **            | Power          |
| >, <, ==      | Comparison     |
| sum(), mean() | Aggregation    |

---

# Interview Questions

### What is Vectorization?

Vectorization is the process of performing operations on entire arrays without explicit loops.

### Why are NumPy operations faster than Python loops?

Because NumPy operations are implemented in optimized C code and use vectorization.

### What are Aggregation Functions?

Functions that summarize data, such as sum(), mean(), min(), and max().

---

# One-Line Revision

NumPy array operations allow fast mathematical calculations on entire arrays using vectorization.
